CREATE TABLE CUSTOMER (
  CNum VARCHAR(10) NOT NULL,
  CName VARCHAR(15) NOT NULL,
  CEmail VARCHAR(30) NOT NULL,
  PRIMARY KEY (CNum)
);

CREATE TABLE MEMBER (
  CClub VARCHAR(15) NOT NULL,
  CNum VARCHAR(10) NOT NULL,
  PRIMARY KEY (CClub, CNum),
  FOREIGN KEY (CNum) REFERENCES CUSTOMER(CNum)
);

CREATE TABLE ELITEMEMBER (
  CClub VARCHAR(15) NOT NULL,
  CNum VARCHAR(10) NOT NULL,
  DiscountPercent INT NOT NULL,
  PRIMARY KEY (CClub, CNum),
  FOREIGN KEY (CClub, CNum) REFERENCES MEMBER(CClub, CNum)
);

CREATE TABLE REGULARMEMBER (
  CClub VARCHAR(15) NOT NULL,
  CNum VARCHAR(10) NOT NULL,
  PointstoUpgrade INT NOT NULL,
  PRIMARY KEY (CClub, CNum),
  FOREIGN KEY (CClub, CNum) REFERENCES MEMBER(CClub, CNum)
);

CREATE TABLE PRODUCT (
  ProID VARCHAR(10) NOT NULL,
  ProName VARCHAR(30) NOT NULL,
  ProDes VARCHAR(50) NULL,
  UnitPrice  DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (ProID)
);

CREATE TABLE PURCHASE (
  PID VARCHAR(10) NOT NULL,
  CNum VARCHAR(10) NOT NULL,
  PDate DATE NOT NULL,
  ProID VARCHAR(10) NOT NULL,
  Quantity INT NOT NULL,
  PRIMARY KEY (PID),
  FOREIGN KEY (CNum) REFERENCES CUSTOMER(CNum),
  FOREIGN KEY (ProID) REFERENCES PRODUCT(ProID)
);
